# Epic Technical Context
name: epic-tech-context
description: "Generate a comprehensive Technical Specification from PRD and Architecture with acceptance criteria and traceability mapping"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated
context_dir: "{config_source}:dev_ephemeral_location/stories"
sprint_status: "{context_dir}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Runtime variables (captured during workflow execution)
project_level: runtime-captured
project_type: runtime-captured
development_context: runtime-captured
epic_scope: runtime-captured
technical_complexity: runtime-captured
epic_num: runtime-captured
epic_id: runtime-captured

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed (epic_num from context)
input_file_patterns:
  prd:
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"
  gdd:
    whole: "{output_folder}/*gdd*.md"
    sharded: "{output_folder}/*gdd*/index.md"
  architecture:
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/index.md"
  ux_design:
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
  epics:
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
  document_project:
    sharded: "{output_folder}/index.md"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/4-implementation/epic-tech-context"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/template.md"
checklist: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{context_dir}/tech-spec-epic-{{epic_id}}.md"
traceability_matrix_file: "{output_folder}/traceability-matrix-epic-{{epic_id}}.md"
acceptance_criteria_file: "{output_folder}/acceptance-criteria-epic-{{epic_id}}.md"

# Required input documents
required_inputs:
  - prd: "Product Requirements Document"
  - architecture: "Architecture specification or design"
  - epics: "Epic definitions and stories"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed (epic_num from context)
input_file_patterns:
  prd:
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"
  gdd:
    whole: "{output_folder}/*gdd*.md"
    sharded: "{output_folder}/*gdd*/index.md"
  architecture:
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/index.md"
  ux_design:
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
  epics:
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
  document_project:
    sharded: "{output_folder}/index.md"
  product_brief:
    whole: "{output_folder}/*brief*.md"
    sharded: "{output_folder}/*brief*/index.md"
  research:
    whole: "{output_folder}/*research*.md"
    sharded: "{output_folder}/*research*/index.md"

# Validation requirements
validation_criteria:
  - technical_feasibility: "All technical requirements must be feasible with current technology stack"
  - resource_availability: "Required resources and skills must be available"
  - timeline_realism: "Implementation timeline must be realistic"
  - risk_assessment: "Technical risks must be identified and mitigated"
  - traceability_completeness: "All requirements must trace to technical specifications"

standalone: true
